packages:
  - "app/*"
  - "app/Frontend/*"
  - "packages/*"

onlyBuiltDependencies:
  - bcrypt
  - esbuild
  - sharp
  - unrs-resolver

allowBuilds:
  '@scarf/scarf': true
  bcrypt: true
  esbuild: true
  msgpackr-extract: true
  sharp: true
  unrs-resolver: true
